---
title: "Projeto"
author: "Marcos Vinicius Troiano"
date: "20 de junho de 2023"
lang: pt
format: 
  html:
    code-tools: true
    code-fold: true
    default-image-extension: png
    page-layout: article
jupyter: python3
---

!pip install pandas
import pandas as pd 
!pip install ipeadatapy
import ipeadatapy as ip

In [2]:
ip.metadata(big_theme="Regional", country="BRA", frequency="Anual")

,CODE,NAME,COMMENT,LAST UPDATE,BIG THEME,SOURCE ACRONYM,SOURCE,SOURCE URL,FREQUENCY,MEASURE,UNIT,SERIES STATUS,THEME CODE,COUNTRY,NUMERICA
543,CONSUMOCOM,Energia elétrica - consumo final energia - com...,A energia elétrica no Brasil é dada através de...,2023-04-25T09:46:00.78-03:00,Regional,MME,"Ministério de Minas e Energia, Balanço Energét...",www.mme.gov.br,Anual,MWh,None,None,2,BRA,True
544,CONSUMOIND,Energia elétrica - consumo final energia - ind...,A energia elétrica no Brasil é dada através de...,2023-04-25T09:46:00.943-03:00,Regional,MME,"Ministério de Minas e Energia, Balanço Energét...",www.mme.gov.br,Anual,MWh,None,None,2,BRA,True
545,CONSUMOOUT,Energia elétrica - consumo final energia - não...,A energia elétrica no Brasil é dada através de...,2023-04-25T09:46:01.097-03:00,Regional,MME,"Ministério de Minas e Energia, Balanço Energét...",www.mme.gov.br,Anual,MWh,None,None,2,BRA,True
546,CONSUMORES,Energia elétrica - consumo final energia - res...,A energia elétrica no Brasil é dada através de...,2023-04-25T09:46:00.623-03:00,Regional,MME,"Ministério de Minas e Energia, Balanço Energét...",www.mme.gov.br,Anual,MWh,None,None,2,BRA,True
547,CONSUMOTOT,Energia elétrica - consumo final energia - qua...,A energia elétrica no Brasil é dada através de...,2023-04-25T09:46:00.453-03:00,Regional,MME,"Ministério de Minas e Energia, Balanço Energét...",www.mme.gov.br,Anual,MWh,None,None,2,BRA,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9673,PIBSDE,PIB Estadual (valor adicionado a preços básico...,O produto interno bruto (PIB) é o total dos be...,2023-06-07T11:10:01.083-03:00,Regional,IBGE,Instituto Brasileiro de Geografia e Estatística,www.ibge.gov.br,Anual,"R$ (mil), a preços do ano 2010",,None,81,BRA,True
9674,PIBSE,PIB Municipal (valor adicionado a preços básic...,O produto interno bruto (PIB) é o total dos be...,2023-06-02T19:20:05.01-03:00,Regional,IBGE,Instituto Brasileiro de Geografia e Estatística,www.ibge.gov.br,Anual,"R$ (mil), a preços do ano 2010",,None,81,BRA,True
9675,PIBSEE,PIB Estadual (valor adicionado a preços básico...,O produto interno bruto (PIB) é o total dos be...,2023-06-07T11:10:01.31-03:00,Regional,IBGE,Instituto Brasileiro de Geografia e Estatística,www.ibge.gov.br,Anual,"R$ (mil), a preços do ano 2010",,None,81,BRA,True
9676,PIBTAE,PIB Estadual (valor adicionado a preços básico...,O produto interno bruto (PIB) é o total dos be...,2023-06-07T11:10:00.643-03:00,Regional,IBGE,Instituto Brasileiro de Geografia e Estatística,www.ibge.gov.br,Anual,"R$ (mil), a preços do ano 2010",,None,81,BRA,True
9677,PIBTE,PIB Estadual (valor adicionado a preços básico...,O produto interno bruto (PIB) é o total dos be...,2023-06-07T11:10:01.953-03:00,Regional,IBGE,Instituto Brasileiro de Geografia e Estatística,www.ibge.gov.br,Anual,"R$ (mil), a preços do ano 2010",,None,81,BRA,True

In [25]:
import csv
base = ip.metadata(big_theme="Regional", country="BRA", frequency="Quinquenal")
lista = list(base['CODE'])
for i in lista:
    ip.timeseries(i).to_csv(i + '.csv', sep=';')

In [78]:
arquivo = "EMPSE.csv" 
dt = pd.read_csv(arquivo, sep=';') 
dt.head()

,DATE,CODE,RAW DATE,TERCODIGO,YEAR,NIVNOME,VALUE (Pessoa)
0,1970-01-01,EMPSE,1970-01-01T00:00:00-02:00,314940,1970,AMC 70-00,2.0
1,1970-01-01,EMPSE,1970-01-01T00:00:00-02:00,3149408,1970,Municípios,2.0
2,1970-01-01,EMPSE,1970-01-01T00:00:00-02:00,250410,1970,AMC 70-00,3.0
3,1970-01-01,EMPSE,1970-01-01T00:00:00-02:00,2504108,1970,Municípios,3.0
4,1970-01-01,EMPSE,1970-01-01T00:00:00-02:00,240040,1970,AMC 70-00,4.0

In [77]:
dado = dt.iloc[:, -1]
print(dado.head(5))

0    2.0
1    2.0
2    3.0
3    3.0
4    4.0
Name: VALUE (Pessoa), dtype: float64

In [81]:
def soma(dado):
    somar = 0
    for i, item in enumerate(dado):
        if i < 5:  # limita a soma aos cinco primeiros dados
            somar = somar + float(item)
        else:
            break
    return somar

resultado = soma(dado.head(5))
print(resultado)

14.0

In [87]:
def media(dado):
    med = dado.head(5).mean()
    return med

resultadoMedia = media(dado)
print(resultadoMedia)

2.8